model:
  name: craft_ocr
  framework: pytorch_ipex

quantization:
  calibration:
    sampling_size: 10, 50

evaluation:
  accuracy:
    metric:
      topk: 1

tuning:
  accuracy_criterion:
    relative: 0.01                           # the tuning target of accuracy loss percentage: 1%
  exit_policy:
    timeout: 10
  random_seed: 9527                            # random seed
